/**
 * Generate SVG path for a rectangle with optional rounded corners
 * @param {Object} shape - Shape configuration
 * @returns {string} SVG path d attribute
 */
export function generateSvgPath(shape) {
  const { width, height, cornerRadius } = shape
  const r = Math.min(cornerRadius, Math.min(width, height) / 2)

  if (r <= 0) {
    // Simple rectangle without rounded corners
    return `M0,0 L${width},0 L${width},${height} L0,${height} Z`
  }

  // Rectangle with rounded corners
  return `
    M${r},0
    L${width - r},0
    Q${width},0 ${width},${r}
    L${width},${height - r}
    Q${width},${height} ${width - r},${height}
    L${r},${height}
    Q0,${height} 0,${height - r}
    L0,${r}
    Q0,0 ${r},0
    Z
  `.replace(/\s+/g, ' ').trim()
}

/**
 * Generate complete SVG file content
 * @param {Object} shape - Shape configuration
 * @returns {string} Complete SVG file content
 */
export function generateSvgFile(shape) {
  const { width, height } = shape
  const pathD = generateSvgPath(shape)
  
  // Convert cm to mm for standard CNC compatibility (1cm = 10mm)
  // ViewBox in cm, actual dimensions in mm for precision
  const widthMm = width * 10
  const heightMm = height * 10

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     width="${widthMm}mm" 
     height="${heightMm}mm" 
     viewBox="0 0 ${width} ${height}">
  <title>Folplex Vector - ${width}x${height}cm</title>
  <desc>Generated by Folplex Vector for CNC machining</desc>
  <metadata>
    <folplex:info xmlns:folplex="http://folplex.pl/vector">
      <folplex:unit>cm</folplex:unit>
      <folplex:width>${width}</folplex:width>
      <folplex:height>${height}</folplex:height>
      <folplex:cornerRadius>${shape.cornerRadius}</folplex:cornerRadius>
    </folplex:info>
  </metadata>
  <path d="${pathD}" 
        fill="none" 
        stroke="#000000" 
        stroke-width="0.1"
        stroke-linecap="round"
        stroke-linejoin="round"/>
</svg>`
}

/**
 * Generate SVG element for embedding (for PDF export)
 * @param {Object} shape - Shape configuration
 * @returns {SVGElement} SVG DOM element
 */
export function generateSvgElement(shape) {
  const { width, height } = shape
  const pathD = generateSvgPath(shape)

  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  svg.setAttribute('xmlns', 'http://www.w3.org/2000/svg')
  svg.setAttribute('width', `${width * 10}mm`)
  svg.setAttribute('height', `${height * 10}mm`)
  svg.setAttribute('viewBox', `0 0 ${width} ${height}`)

  const path = document.createElementNS('http://www.w3.org/2000/svg', 'path')
  path.setAttribute('d', pathD)
  path.setAttribute('fill', 'none')
  path.setAttribute('stroke', '#000000')
  path.setAttribute('stroke-width', '0.1')
  path.setAttribute('stroke-linecap', 'round')
  path.setAttribute('stroke-linejoin', 'round')

  svg.appendChild(path)
  return svg
}

/**
 * Download file utility
 * @param {string} content - File content
 * @param {string} filename - Name of the file
 * @param {string} mimeType - MIME type
 */
export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  
  URL.revokeObjectURL(url)
}
